# Generated by Django 5.0.4 on 2024-07-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subscriptionhistory_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='credits',
            field=models.IntegerField(default=50),
        ),
    ]
