# Generated by Django 5.0.4 on 2024-07-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_credits_id_subscriptions_delete_subscriptionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='times_subscribed',
            field=models.IntegerField(default=0),
        ),
    ]
