# Generated by Django 5.0.4 on 2024-07-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_subscriptions_times_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='subscription_info',
            field=models.TextField(default=''),
        ),
    ]
